name: Create Release
description: Create the GitHub CLI extension release
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - 'tags/v*'
      
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build and release binaries
        uses: cli/gh-extension-precompile@v2
        with:
            go_version_file: go.mod
            generate_attestations: true
